In [10]:
from Person import Person
from Citizen import Citizen

p = Person("Juan")
c = Citizen("David", "Colombia")
c.name = "carlos"

# llamando a los métodos modificados explícitamente del padre
print(p.__str__())
print(c.__str__())

The Person is named Juan
The Person is named carlos, and comes from Colombia


In [2]:
# llamando a los métodos implícitos del padre
print(p.get_name())
print(c.get_name())

my name is Juan
my name is David


In [3]:
# la clase Person será referenciada con un alias 
a = Person
m = a("Pedro")
print(m.name)
print(m.get_name())
print(m.__str__())

Pedro
my name is Pedro
The Person is named Pedro


In [2]:
def scope_test():
    def do_local():
        # This assignment is not printed in the local scope. Thus, it should not be seen
        # outside the do_local() function.
        spam = "local spam"

    def do_nonlocal():
        # nonlocal variable is taken in the function's scope. Assignment will be seen in the 
        # scope_test() function scope, but not outside it.
        nonlocal spam
        spam = "nonlocal spam"

    def do_global():
        # takes the global variable spam and modifies its value
        global spam
        spam = "global spam"

    # definition in the nonlocal scope
    spam = "test spam"
    do_local()
    print("After local assignment:", spam)
    
    do_global()
    # although the global definition was modified, it is printed the 'nonlocal' 
    # value because of the scope's visibility. To print the global value, then the 
    # global keyword should've been used
    print("After global assignment:", spam) 
    
    # only modifies the nonlocal scope definition of the variable. Thus, it should not 
    # change the global value
    do_nonlocal()
    print("After nonlocal assignment:", spam)


scope_test()
print("In global scope:", spam)

After local assignment: test spam
After global assignment: test spam
After nonlocal assignment: nonlocal spam
In global scope: global spam


In [5]:
import numpy as np

mat_a = (np.linspace(1, 9, 9).reshape((3, 3))).astype('int')
mat_b = ((mat_a * 5) + np.random.normal(0, 3, (3, 3))).astype('int')
print(mat_a)
print('---------------')
print(mat_b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
---------------
[[ 4  5  7]
 [20 23 32]
 [34 35 35]]


In [6]:
op = np.matmul

# np.matmul(mat_a, mat_b)
print(op(mat_a, mat_b))
print(op)

[[146 156 176]
 [320 345 398]
 [494 534 620]]
<built-in function matmul>


In [7]:
print(c)
print(c.get_name)
print(c.get_name())

The Person is named David, and comes from Colombia
<bound method Person.get_name of <Citizen.Citizen object at 0x0535D1D0>>
my name is David


In [8]:
c.get_name = lambda: "no recuerdo mi nombre"
c.get_name = lambda x: x ** 2

c.get_name(9)

81

In [9]:
def reverse(data):
    for index in range(len(data)-1, -1, -1):
        yield data[index]


text = ""
for i in reverse('me encuentro en reverso'):
    text += i
print(text)

osrever ne ortneucne em
